builders:
  protoc_builder:
    import: "package:protoc_builder/protoc_builder.dart"
    builder_factories: ["getBuilder"]
    build_extensions: {
      ".proto": [".dart", ".pb"]
    }
    auto_apply: dependents
